if ($http_x_forwarded_proto = 'http') {
  return 301 https://$server_name$request_uri;
}

resolver dns01.topcoder.com valid=30s;
client_max_body_size 30M;
set $ebsHost "{{ENV_NETLIFY}}";
proxy_pass https://$ebsHost$request_uri;

proxy_ssl_server_name on;
proxy_ssl_name "{{ENV_NETLIFY}}";
proxy_ssl_session_reuse off;

#proxy_set_header        Host     "{{ENV_NETLIFY}}";
#proxy_set_header        Connection              "";
#proxy_set_header        X-Forwarded-Host        $http_host;

#proxy_ssl_protocols TLSv1.2 TLSv1.3;

#proxy_set_header Host $ebsHost;


# proxy_ssl_name $ebsHost;
# proxy_ssl_server_name on;


#proxy_ssl_protocols TLSv1.2 TLSv1.3;
#proxy_set_header Connection "";

# proxy_ssl_verify off;
#proxy_set_header X-Real-IP $remote_addr;
#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#proxy_set_header X-Forwarded-Proto https;
#proxy_set_header X-Forwarded-Host $http_host;

#proxy_http_version 1.1;
#proxy_cache off;
