version: 0.0
os: linux
files:
  - source: ./src
    destination: /mnt/nginx
  - source: ./dist
    destination: /mnt/nginx
  - source: ./Dockerfile
    destination: /mnt/nginx
  - source: ./build
    destination: /mnt/nginx
  - source: ./run
    destination: /mnt/nginx
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
