version: 0.0
os: linux
files:
  - source: ./Dockerfile
    destination: /mnt/nginx
  - source: ./nginx.conf
    destination: /mnt/nginx
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
