#!/bin/bash -x
./build

ln -s /data/nginx/dist/nginx.conf /etc/nginx/nginx.conf
ln -s /data/nginx/dist/limits.conf /etc/nginx/limits.conf
ln -s /data/nginx/dist/sites-enabled /etc/nginx/sites-enabled
ln -s /data/nginx/dist/includes /etc/nginx/includes

chown -Rf nginx:nginx /data/nginx/dist

nginx -t && nginx && tail -f /dev/null