#!/bin/bash -x

crontab /data/nginxconf/scripts/root.cron
/usr/sbin/cron

if [[ "$PROVIDER" == local ]]; then
	echo "8.8.8.8 dns01.topcoder.com" >> /etc/hosts
fi

#nginx -t && nginx  && tail -f /var/log/nginx/logs/error.log -f /var/log/nginx/logs/access.log
nginx -t && nginx
