#!/bin/bash
cd /tmp/nginx
echo "Stopping nginx server"
docker stop nginx
echo "Removing nginx container"
docker rm nginx
echo "Building new docker conatiner for nginx"
docker build -t nginx .
echo "Starting new docker conatiner for nginx"
docker run -d --name nginx -p 8000:8000 nginx
